### ISSUE TITLE
Please include the 'scandir' module for faster directory listing 

### ISSUE THREAD

**Issue by JackD83** [retrofw/retrofw.github.io#19]
[PyMenu](https://github.com/JackD83/PyMenu) is currently using its own copy of scandir to list files and directories. Its much faster than the default listing and was integrated in later python versions (>3.5)

As scandir is an official module, it could/should be included in the rootfs to be more compatible.

**Comment by pingflood** [comment]
Fixed in the v2.1 release:
https://github.com/retrofw/buildroot/commit/61654fef29cd4dcd2ee15c17239f587c1f0c1b37
