### ISSUE TITLE
RG 300 v1.3 Won't boot

### ISSUE THREAD

**Issue by NickDevoctomy** [retrofw/retrofw.github.io#20]
I've tried several different versions but can't get it to boot on my RG 300 v1.3 (version number displayed right next to the internal SD card slot.

I've tried

2B - Black screen, nothing at all
3B - White screen
5B - White screen

I guess I don't have IPS in this 1.3 version as I have also tried the official IPS version and that doesn't work (just a white screen as with 3B and 5B above).  Just the official RG 300 V2 firmware is working for me at the moment. I've opened it up and can't see anything to suggest what screen it does have in it.

**Comment by duskgao** [comment]
My device is  v1.3 too, I use 2B very well
