### ISSUE TITLE
suspend does not work in LDK square RETROFW 2.0 type 2B

### ISSUE THREAD

**Issue by Ninoh-FOX** [retrofw/retrofw.github.io#23]
the suspend function does not work, this worked fine in version 1.x with the button that was dedicated.

I have also seen that the screen flickers when the boot logo comes out and the screen flickers on emulators such as GPSP.

**Comment by pingflood** [comment]
@Ninoh-FOX does it go into suspend mode after the timeout defined in GMenuNX settings?

**Comment by Ninoh-FOX** [comment]
The screen of with the time settings, but not work with the dedicate button how in the v1.2

**Comment by pingflood** [comment]
Closing because that's how the system works and it was clarified directly to the author.
