### ISSUE TITLE
Does exist any update for PAP Kiii plus?

### ISSUE THREAD

**Issue by manuelruiz1240** [retrofw/retrofw.github.io#26]
I would like that this were like cfw Rogue (at least include battery indicator), i think everybody has forgot this console (rs-100 https://www.dhresource.com/600x600/f2/albu/g7/M00/4F/5F/rBVaSVu_S6iAJoGmAABDH-fQSzc901.jpg)

**Comment by pingflood** [comment]
Sorry, RetroFW can't support for PAP devices.
