### ISSUE TITLE
The infamous RS-97 Plus V1 with the 30FPS LCD 

### ISSUE THREAD

**Issue by JohnMurga** [retrofw/retrofw.github.io#27]
I remember that it didn't used to be supported ...

But now I don't even see it mentioned anywhere :|

Will any of the firmware types work with it ?

**Comment by pingflood** [comment]
Sorry, RS97 Plus V1 is unsupported and is not planned to be supported.

Besides it having a really bad LCD panel, that device uses a SLCD interface and RetroFW kernel can't be properly built for it.
