### ISSUE TITLE
Add Game&Watch Clone by steward to software list

### ISSUE THREAD

**Issue by Cralex** [retrofw/retrofw.github.io#30]
Some time ago, steward appeared without warning on the RetroFW discord server and uploaded a clone of various Game&Watch games. Since then, I haven’t heard of any updates being made to it, so I figure it might as well be added to the software list as-is. Here’s a like for reference: https://cdn.discordapp.com/attachments/591959465419603998/703053861685821550/gamewatch_retrofw_20200313_0.opk

**Comment by pingflood** [comment]
There's some licensing issues with the [madrigal simulator and assets](http://www.madrigaldesign.it/sim/file.php?id=1) and I'd rather not risk our repository hosting it. 

When the opk was shared, Steward-Fu said he is still working on it and would release the updated sources in his github.

I'll close this for now but I'll keep one eye on Steward's repositories and link it as soon as he updates it :+1:
