### ISSUE TITLE
Black Dots on LDK Device

### ISSUE THREAD

**Issue by shadow7710** [retrofw/retrofw.github.io#31]
Hi everyone,

Today when switching on my LDK Horizontal device I noticed it was displaying black dots on the screen, even when entering a game it still showed the dots, could this be a problem with the device itself? Uploaded a couple of pictures (hopefully they did) to show my problem. 

Thanks 👍 
![IMG_0057](https://user-images.githubusercontent.com/64869183/81115072-0e98b800-8f1b-11ea-8c17-9faf20fa61b5.jpeg)
![IMG_0059](https://user-images.githubusercontent.com/64869183/81115089-148e9900-8f1b-11ea-97e3-21b1d38d4eff.jpeg)

**Comment by pingflood** [comment]
Hardware related and not a firmware issue.
