### ISSUE TITLE
White screen RS-97 v2.0

### ISSUE THREAD

**Issue by 2010ngojo** [retrofw/retrofw.github.io#33]
Getting a white screen for the following versions: 2.0, 2.1, 2.2 for RS-97 v2.0. Used type 2A image. Seems like it boots up and creates the partitions and directories, but nothing shows up. No boot/splash screen, just a white screen. Screen flashes once or two upon initial boot up after flashing the image file. Brightness control works. Tried multiple mSD cards. Original firmware works with the card I flashed.

**Comment by pingflood** [comment]
White screen means you are using the wrong firmware type for your device.
Try with other firmware types until you find the one that matches the screen driver for your unit.

As it's not a bug in the firmware itself this issue is being closed.

**Comment by 2010ngojo** [comment]
Type 1A works for rev. 2.0. Several others with rev. 2.0 board have stated the same thing. Something is mislabeled here.
