### ISSUE TITLE
Documentation: RS-97 v2.0 wrongly listed in table to be Type 2A

### ISSUE THREAD

**Issue by keeyeong** [retrofw/retrofw.github.io#35]
In release 2.0, there are 2 tables in the release notes, and RS-97 v2.0 (Retro Game v2.0) is wrongly listed in the 1st table as being compatible with Type 2A; where the second table lists it correctly as compatible with Type 1A. 

Unfortunately all subsequent release notes only includes the 1st table with the error and it took me a while to figure out when flashing it on my RS-97 v2.0 and had to do a little investigation myself.

**Comment by pingflood** [comment]
@keeyeong there are several revisions of these devices.
Some of them mixes different boards (the called RG V1.0, V1.0 S, V2.0, etc..) with different screen modules.
If you got a "V2.0" but with a V1.0 module, the firmware Type 1A will work on it.

The table is just for reference of the "historic" hardware revision, but if you got a different mix of board and LCD module, the other firmware type will work on it. It's just trial and error.
