### ISSUE TITLE
TV-OUT

### ISSUE THREAD

**Issue by actraiser30** [retrofw/retrofw.github.io#36]
Hello is the LDK Game (square) and the Retro Game 300 IPS support the TV-OUT connection with the latest RetroFW 2.2 firmware??

Thanks

**Comment by actraiser30** [comment]
i did a question cant you answer??

**Comment by scooterpsu** [comment]
It's in the [changelog](https://retrofw.github.io/CHANGELOG) as a feature added in 2.0. So it's an "invalid" issue, in that it's already answered.

**Comment by actraiser30** [comment]
ok thanks

**Comment by actraiser30** [comment]
any change you can add support for the latest bittboy 3.5 ??

**Comment by scooterpsu** [comment]
RetroFW is for a very specific type of hardware. Bittboy uses a completely different architecture (ARM vs MIPS). 

Also please don't use this to ask questions, it emails everyone that follows the project each time you do. The official [Discord server](https://discord.gg/CX67MCH) is significantly better for this.
