### ISSUE TITLE
after rs07 support, why not aiwo g1000 support?

### ISSUE THREAD

**Issue by ahahahaah** [retrofw/retrofw.github.io#41]
hello,
since end of last year retrofw supports the rs07, so is it an option to support aiwo g1000?
this device is not followed by the manufacturer and the actual cfw is not as easy to install as retrofw and is not as functionnal as retrofw.
this machine is great but the software is not fully painstaking.
Someone know if it is possible to support it?
thx

**Comment by jbanes** [comment]
Unfortunately the AIWO G1000 is an Android-based device running a 64-bit ARM processor. An RK3128 chip to be precise. Some AliExpress sellers mistakenly list it with the same specs as the RS-07. e.g. "Dual-Core 528MHz" This is incorrect. The device is currently incompatible with RetroFW software.

If RetroFW supports ARM chips at some point in the future, we can revisit. Sorry about that.
