### ISSUE TITLE
LDK Game Vertical

### ISSUE THREAD

**Issue by actraiser30** [retrofw/retrofw.github.io#42]
Hello,is it possible to put in the next firmware version for LDK Game Vertical version the TV-OUT feature back?

thanks

**Comment by symbios24** [comment]
Same problem here with rg300 can you put in the next release a setting in the options to adjust overscan or to fit to screen?

**Comment by pingflood** [comment]
Not possible to change the overscan on device side. It's a hardware limitation.
The only possible fix is to change it on the TV itself.

**Comment by actraiser30** [comment]
At least is it possible to put a resolution setting eg: 640x480 ?

Στις Παρ, 28 Αυγ 2020, 21:32 ο χρήστης pingflood <notifications@github.com>
έγραψε:

**Comment by jbanes** [comment]
Composite outputs don’t have a resolution per se. It’s all down to the timing of the change in signal. I’m afraid that what we have currently is the best the hardware can put out.

**Comment by symbios24** [comment]
That's strange all my devices with rca cables work correct the problem happens only in my LDK Game handheld are you sure its not a firmware issue??
