### ISSUE TITLE
release of last remaining source code

### ISSUE THREAD

**Issue by Poligraf** [retrofw/retrofw.github.io#58]
@pingflood , there are still a handful of things for which the source code is not released like recovery menu and I think the gmenunx binary.

I would like to request that they are released even if they are WIP zip, as long as we can fix the buildroot so that `make` can create an image.

**Comment by Poligraf** [comment]
@jbanes as well do you have access to the retrofw binary source ?

**Comment by pingflood** [comment]
Done: https://github.com/retrofw/recovery . 
gmenunx repository is in sync with the last binary I was using previously.

**Comment by Poligraf** [comment]
Omg awesome. finaly we will be able to release a new retrofw version :D

**Comment by Poligraf** [comment]
@pingflood not sure why I cant https://github.com/retrofw/recovery but oh well, worst case scenario will create a new wiki page.

Thanks for your help, here to hoping one day you return (even if it just to say hi)

**Comment by pingflood** [comment]
You can't what? Build or access? :thinking:

**Comment by Poligraf** [comment]
Oops sorry, typed the url wrong
I can not edit https://github.com/retrofw/retrofw.github.io since my link has expired.

 I am still of the opinion that the firmware should live on for a bit longer and get some bumps (and a cleaner newer buildroot at least).
 
 For example I would like to release  
 
 https://drive.google.com/drive/folders/1TyrV90kvCoQYWfCA35ZVFvGZNKyVJNcf
to https://github.com/retrofw/retrofw.github.io as 2.3 release candidate. 

The link granting me access has expired

**Comment by pingflood** [comment]
Oh, I see..

I wasn't aware of this restriction. I'll change your role in the RetroFW org, but I'm _summoning_ @jbanes and @retromsx here so they can review the permissions, as I don't have enough knowledge to manage this kind of thing :sweat_smile: 

I'll close this issue for now :wink:

**Comment by Poligraf** [comment]
thanks all looks good, in case I do not hear from you have a merry X mas

**Comment by Poligraf** [comment]
I am not sure if any of you still care, but wanted to let you know that I managed to bump retrofw to 2021-11

still have some minor issues and not sure why /proc/jz/keyboard is not working anymore but yeah :D

https://github.com/Poligraf/buildroot/tree/2021.11.x
