### ISSUE TITLE
No Music in GZDoom, EDuke, Decent

### ISSUE THREAD

**Issue by drtekGER** [retrofw/retrofw.github.io#59]
Hi,

2.3 rc2 is really impressive in terms of performance.

Sadly CZDoom, Eduke and Descent are missing the music.

On 2.2 everything works fine music wise.

Thx for your efforts!

**Comment by Poligraf** [comment]
I am not entirely sure if CZDOOM had music working if this is the gameblabla port. Can you confirm it has music in 2.2?

Also where did you grab eduke and descent opk from?

Is it from the official ports wiki?

**Comment by drtekGER** [comment]
Hi,

I copied everything over from my 2.2 SD Card. All opks are only from the
wiki.

Seems like some sort of system wide Midi-Music-Driver issue.

I love your work, thanks!

Poligraf ***@***.***> schrieb am Sa., 29. Jan. 2022, 10:41:

**Comment by Poligraf** [comment]
yes bug verified thanks.

**Comment by Poligraf** [comment]
Thank you for bug reporting.

Issue is now fixed https://github.com/Poligraf/buildroot/commit/cfa145ea80513552ad5d3d31743b8c335d179094

To fix your problem just copy the rootfs.squashfs file from here: https://github.com/Poligraf/retrofw_junk/releases/download/2.3-3/rootfs.squashfs over your old file.

You do not need to reinstall or reimage anything. No data will be lost while you do this. This will make all the affected applications work. 

Tested duke.
